=== c-chapellier/42_rt/configs/scene.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="vec3type">
    <xs:attribute name="x" type="xs:float" use="required"/>
    <xs:attribute name="y" type="xs:float" use="required"/>
    <xs:attribute name="z" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="cameratype">
    <xs:sequence>
      <xs:element name="position" type="vec3type"/>
      <xs:element name="direction" type="vec3type"/>
      <xs:element name="up" type="vec3type"/>
    </xs:sequence>
    <xs:attribute name="aperture" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:simpleType name="uint8type">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="255"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="colortype">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="r" type="uint8type" use="required"/>
    <xs:attribute name="g" type="uint8type" use="required"/>
    <xs:attribute name="b" type="uint8type" use="required"/>
  </xs:complexType>

  <xs:complexType name="colorstype">
    <xs:sequence>
      <xs:element name="color" type="colortype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="uniformtype">
    <xs:attribute name="color" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="chessboardtype">
    <xs:attribute name="color1" type="xs:string" use="required"/>
    <xs:attribute name="color2" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="texturefromfiletype">
    <xs:attribute name="filename" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="refractivetype">
    <xs:attribute name="n" type="xs:float" use="required"/>
  </xs:complexType>

  <xs:complexType name="objecttype">
    <xs:sequence>
      <xs:element name="translation" type="vec3type"/>
      <xs:element name="rotation" type="vec3type"/>
      <xs:element name="scale" type="vec3type"/>
      <xs:choice>
        <xs:element name="diffuse" ><xs:complexType/></xs:element>
        <xs:element name="metal" ><xs:complexType/></xs:element>
        <xs:element name="mirror" ><xs:complexType/></xs:element>
        <xs:element name="refractive" type="refractivetype"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="uniform" type="uniformtype"/>
        <xs:element name="chessboard" type="chessboardtype"/>
        <xs:element name="texturefromfile" type="texturefromfiletype"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="torustype">
    <xs:sequence>
      <xs:element name="base" type="objecttype"/>
      <xs:element name="R" type="xs:float"/>
      <xs:element name="r" type="xs:float"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="objectstype">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="sphere" type="objecttype" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="torus" type="torustype" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="plane" type="objecttype" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="mobiustape" type="objecttype" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="box" type="objecttype" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="scenetype">
    <xs:sequence>
      <xs:element name="height" type="xs:positiveInteger"/>
      <xs:element name="width" type="xs:positiveInteger"/>
      <xs:element name="precision" type="xs:positiveInteger"/>
      <xs:element name="camera" type="cameratype"/>
      <xs:element name="colors" type="colorstype"/>
      <xs:element name="objects" type="objectstype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="scene" type="scenetype"/>

</xs:schema>

=== c-chapellier/42_rt/configs/fresnelsurface.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="70" y="0" z="0" />
    <direction x="-1" y="0" z="0" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
  </colors>

  <objects>
    <fresnelsurface>
      <base>
        <translation x="0" y="0" z="0" />
        <rotation x="0" y="31" z="45" />
        <scale x="1" y="1" z="1" />
        <diffuse />
        <uniform color="red" />
      </base>
      <a>10</a>
      <b>5</b>
      <c>20</c>
    </fresnelsurface>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/dupincyclide_open.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="0" y="0" z="5" />
    <direction x="0" y="0" z="-1" />
    <up x="0" y="1" z="0" />
  </camera>

  <colors>
  </colors>

  <objects>
    <dupincyclide>
      <base>
        <translation x="0" y="0" z="0" />
        <rotation x="0" y="0" z="0" />
        <scale x="1" y="1" z="1" />
        <diffuse />
        <texturefromfile filename="./textures/astronomy/2k_moon.jpg" />
      </base>
      <a>1</a>
      <b>0.99</b>
      <c>0.2</c>
      <d>0.23</d>
    </dupincyclide>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/textures.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="3.5" y="0" z="0" />
    <direction x="-1" y="0" z="0" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
  </colors>

  <objects>
    <!-- <sphere>
      <translation x="0" y="0" z="0" />
      <rotation x="0" y="30" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="air_force_blue_raf" color2="air_force_blue_usaf" />
      <texturefromfile filename="./textures/astronomy/2k_earth_daymap.jpg" />
    </sphere> -->
    <!-- <torus>
      <base>
        <translation x="0" y="0" z="0" />
        <rotation x="0" y="45" z="0" />
        <scale x="1" y="1" z="1" />
        <diffuse />
      <texturefromfile filename="./textures/astronomy/2k_earth_daymap.jpg" />
      </base>
      <R>2</R>
      <r>1</r>
    </torus> -->
    <mobiustape>
      <translation x="0" y="0" z="0" />
      <rotation x="0" y="90" z="-90" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <texturefromfile filename="./textures/astronomy/2k_earth_daymap.jpg" />
    </mobiustape>
    <plane>
      <translation x="-4" y="0" z="0" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <texturefromfile filename="./textures/astronomy/2k_earth_daymap.jpg" />
    </plane>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/mirror_torus.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="12" y="0" z="0" />
    <direction x="-1" y="0" z="0" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
  </colors>

  <objects>
    <torus>
      <base>
        <translation x="0" y="0" z="0" />
        <rotation x="0" y="25" z="0" />
        <scale x="1" y="1" z="1" />
        <refractive n="2.4" />
        <uniform color="white" />
      </base>
      <R>3</R>
      <r>1</r>
    </torus>
    <plane>
      <translation x="-6" y="0" z="0" />
      <rotation x="0" y="0" z="45" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="air_force_blue_raf" color2="air_force_blue_usaf" />
    </plane>
    <plane>
      <translation x="-6" y="0" z="0" />
      <rotation x="0" y="0" z="-45" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="air_force_blue_raf" color2="air_force_blue_usaf" />
    </plane>
    <plane>
      <translation x="13" y="0" z="0" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="air_force_blue_raf" color2="air_force_blue_usaf" />
    </plane>
    <plane>
      <translation x="0" y="0" z="13" />
      <rotation x="0" y="90" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="android_green" color2="antique_ruby" />
    </plane>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/plane.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="5" y="0" z="0" />
    <direction x="-1" y="0" z="0" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
    <color name="red" r="200" g="30" b="30" />
    <color name="lightred" r="170" g="30" b="30" />
  </colors>

  <objects>
    <plane>
      <translation x="0" y="0" z="0" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="red" color2="lightred" />
    </plane>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>4</precision>
    
  <camera aperture="90">
    <position x="12" y="0" z="10" />
    <direction x="-1" y="0" z="-0.5" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
  </colors>

  <objects>
    <plane>
      <translation x="0" y="0" z="0" />
      <rotation x="0" y="85" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <chessboard color1="air_force_blue_raf" color2="air_force_blue_usaf" />
    </plane>
    <sphere>
      <translation x="0" y="0" z="1" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <texturefromfile filename="./textures/bricks2.jpg" />
    </sphere>
    <sphere>
      <translation x="-3" y="1" z="1" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <uniform color="red" />
    </sphere>
    <sphere>
      <translation x="-20" y="4" z="2" />
      <rotation x="0" y="0" z="0" />
      <scale x="2" y="2" z="2" />
      <diffuse />
      <uniform color="apple_green" />
    </sphere>
    <sphere>
      <translation x="-3" y="-5" z="2" />
      <rotation x="0" y="0" z="0" />
      <scale x="2" y="2" z="2" />
      <mirror />
      <texturefromfile filename="./textures/bricks2.jpg" />
    </sphere>
    <sphere>
      <translation x="-6" y="4" z="3" />
      <rotation x="0" y="0" z="0" />
      <scale x="3" y="3" z="3" />
      <refractive n="1.8" />
      <texturefromfile filename="./textures/bricks2.jpg" />
    </sphere>
  </objects>

</scene>

=== c-chapellier/42_rt/configs/refraction.xml
<?xml version="1.0" encoding="UTF-8"?>

<scene
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="scene.xsd"
>
  <height>600</height>
  <width>600</width>
  <precision>1</precision>
    
  <camera aperture="90">
    <position x="3.5" y="0" z="0" />
    <direction x="-1" y="0" z="0" />
    <up x="0" y="0" z="1" />
  </camera>

  <colors>
  </colors>

  <objects>
    <!-- <sphere>
      <translation x="0" y="0" z="0" />
      <rotation x="0" y="30" z="0" />
      <scale x="1" y="1" z="1" />
      <refractive_index n="10" />
      <refractive />
      <uniform color="red" />
    </sphere> -->
    <torus>
      <base>
        <translation x="0" y="0" z="0" />
        <rotation x="0" y="25" z="0" />
        <scale x="1" y="1" z="1" />
        <refractive n="1.3" />
        <uniform color="red" />
      </base>
      <R>1</R>
      <r>0.3</r>
    </torus>
    <plane>
      <translation x="-4" y="0" z="0" />
      <rotation x="0" y="0" z="0" />
      <scale x="1" y="1" z="1" />
      <diffuse />
      <!-- <texturefromfile filename="./textures/astronomy/2k_earth_daymap.jpg" /> -->
      <chessboard color1="white" color2="black" />
    </plane>
  </objects>

</scene>
